version: '3'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      DATABASE_HOSTNAME: db
      DATABASE_PORT: 5432
      DATABASE_NAME: tun-judge
      DATABASE_USERNAME: tun-judge
      DATABASE_PASSWORD: tun-judge
      SESSION_SECRET: secret
    ports:
      - 3000:3000
    depends_on:
      - db
      - redis

  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: tun-judge
      POSTGRES_USER: tun-judge
      POSTGRES_PASSWORD: tun-judge
    volumes:
      - /opt/tun-judge/db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080

  redis:
    image: bitnami/redis:6.0
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - redis-data:/bitnami/redis/data
    ports:
      - 6379:6379

volumes:
  redis-data:
    driver: local
